### ISSUE TITLE
UnsupportedCommandException is thrown when using  ElementActions.type in Appium project

### ISSUE THREAD

**Issue by ShorouqElrakhawy** [MohabMohie/SHAFT_ENGINE#223] opened 2020-12-06 09:01 UTC
**Describe the bug**
Exception org.openqa.selenium.UnsupportedCommandException is thrown when using  ElementActions.type(driver, elementLocator, text); in Appium project

**To Reproduce**
1. Start Appium server and activate a virtual android device
2. Use ElementActions.type(driver, elementLocator, text); 
3. Run

**Expected behavior**
The method should send keys

** Virtual Smartphone**
 - OS: Android 9.0

**Allue report**

[allure-results.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/5648514/allure-results.zip)

**Comment by MohabMohie** [comment] 2020-12-06 13:28
a fix was just pushed for that issue via this new release "4.4.20201206"
note that this release was upgraded to work with jdk 15 so you will need to update your jdk as well.
kindly test and give your feedback, I'm expecting more issues to arise related to that one so I won't close this ticket pending your feedback.

**Comment by ShorouqElrakhawy** [comment] 2020-12-06 13:55
The issue isn't resolved yet
here is an allure report
[allure-results.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/5648846/allure-results.zip)

**Comment by MohabMohie** [comment] 2020-12-06 23:53
Please note that I'm unable to reproduce the issue from my side. Would you kindly examine the locators I used in the below sample, and if the problem persists share a link to the project on github so that I can investigate further?

![image](https://user-images.githubusercontent.com/19201898/101296915-d51c8800-382e-11eb-92cc-b0fcc47a2cc8.png)
![image](https://user-images.githubusercontent.com/19201898/101296930-e9f91b80-382e-11eb-96a8-fbcb7277f07c.png)

**Comment by ShorouqElrakhawy** [comment] 2020-12-07 17:24
After investigation, I found out that the method "isMobileNativeExecution" returns false
reason: the desired capabilities weren't included in the mobile.properties ... instead it was initiated manually in the test class

so generally, ElementActions.type method works perfectly

but it is the only method that doesn't work when desired capabilities are initiated manually in the test class
this is the allure report of the successful run
[allure-results.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/5654161/allure-results.zip)

**Comment by MohabMohie** [comment] 2020-12-07 18:06
Actually none of the element actions should work as expected in that case... I'm surprised :D 

at least the platformName and executionAddress must be set, but for the rest you can override them manually... that's what I did also to use the relative path of the apk file since that's not allowed in the capabilities.

anyway, a bunch of new enhancements are on the way to the mobile section, including automated video recording, and tapping an element using its image... I'll be sure to unify the check and enhance "isMobileNativeExecution" if possible for ElementActions class.

**Closed by MohabMohie** 2020-12-07 18:06 UTC
